# Generated by Django 4.2.16 on 2025-05-27 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='likes',
            field=models.ManyToManyField(related_name='likes_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='subscribes',
            field=models.ManyToManyField(related_name='subs_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
